import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { getAllFilesMetadata } from '../lib/mdx';

const Home: NextPage = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Nico Mellon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>this is my home page</h1>
    </>
  );
};

export default Home;
