import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { getAllFilesMetadata } from '../lib/mdx';

const Home: NextPage = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {posts.map((post) => (
          <Link key={post.slug} href={`/blog/${post.slug}`}>
            <a>
              <h2>{post.title} &rarr;</h2>
              <p>{post.date}</p>
            </a>
          </Link>
        ))}
      </div>
    </>
  );
};

export async function getStaticProps() {
  try {
    const posts = await getAllFilesMetadata();
    return {
      props: { posts },
    };
  } catch (err) {
    console.error(err);
  }
}

export default Home;
